---
title: 'CHELSA downscaling'
author: "Maya Guéguen"
date: "07/05/2018"

output:
  html_document:
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: no
    theme: cerulean
    highlight: monochrome
---

<br/>
<br/>

# Glossary {.tabset .tabset-fade .tabset-pills} 

- **DEM :** Digital Elevation Model,  
3D CG representation of a terrain's surface created from a terrain's elevation data.

- **GWR :** Geographically Weighted Regression,  
outgrowth of ordinary least squares regression (OLS), allowing the relationships between the independent and dependent variables to vary by locality.

- **SVF :** Sky View Factor,  
ratio at a point in space between the visible sky and a hemisphere centered over the analyzed location (Oke 1981).

- **LST :** Land Surface Temperature,

- **SAGA commands :**
    - **calculation : ** Grid &#8594; Calculus &#8594; Grid Calculator
    - **reproject : ** (*Geoprocessing &#8594;*) Projection &#8594; Coordinate Transformation (Grid List)
    - **clip :** Grid &#8594; Grid System &#8594; Clip Grids
    - **clip and reproject :**
    - **GWR :** (*Geoprocessing &#8594;*) Spatial and Geostatistics &#8594; Geographically Weighted Regression
    - **regression :** (*Geoprocessing &#8594;*) Spatial and Geostatistics &#8594; Regression &#8594; Polynomial Trend from Grids
    - **SVF :** Terrain analysis &#8594; Lighting &#8594; Sky View Factor
    - **Solar radiation :** Terrain analysis &#8594; Lighting &#8594; Potential Incoming Solar radiation
    - **LST :** Terrain analysis &#8594; Morphometry &#8594; Land Surface Temperature


<br/>
<br/>


# Precipitation downscaling

### To be done only once

1. **Get data :** CHELSA monthly precipitation : [here](http://chelsa-climate.org/downloads/)

2. **Reproject into equal area projection** (ETRS89) with B-spline interpolation

<br/>

### To do for each required area

1. **Get data :** DEM

2. **Reproject into equal area projection** (ETRS89) with B-spline interpolation

3. **Clip** CHELSA monthly precipitation onto DEM

4. **Compute Geographically Weighted Regression**
    - of CHELSA monthly precipitation in function of DEM
    - with residual correction

<br/>
<br/>



# Temperature downscaling

### To be done only once

1. **Get data :** 
    - CHELSA min/mean/max temperature : [here](http://chelsa-climate.org/downloads/)
    - Earth Env monthly cloud cover : [here](http://www.earthenv.org/cloud)
    - ERA Interim daily temperature (00:00 and 12:00) of model levels from 60 to 33 : [here](http://apps.ecmwf.int/datasets/data/interim-full-daily/levtype=ml/)  
    - USGS and NGA DEM data (GMTED2010, mean 7.5 arc sec) : [here](https://www.usgs.gov/land-resources/eros/coastal-changes-and-impacts/gmted2010?qt-science_support_page_related_con=0#qt-science_support_page_related_con)

<br/>

2. **Compute mean by month and level** for ERA Interim temperature

3. **Reproject into angle conserving projection** (Mercator) with B-spline interpolation :
    - CHELSA min/mean/max temperature
    - Earth Env monthly cloud cover
    - ERA Interim monthly temperature of model levels from 60 to 33 
    - USGS and NGA DEM data (GMTED2010)
    
<br/>

3. **Compute regression** to get Lapse rate
    - of ERA Interim monthly temperature of model levels from 60 to 33 in function of elevation levels
    - with a polynomial of order 1
    - and keep the slope (coeff2)

<br/>

4. **Divide by 10** CHELSA min/mean/max temperature to have degrees

<br/>

### To do for each required area

1. **Get data :** DEM

2. **Reproject into angle conserving projection** (Mercator) with B-spline interpolation

<br/>

3. **Clip** Earth Env monthly cloud cover onto DEM

4. **Compute Geographically Weighted Regression**
    - of Earth Env monthly cloud cover in function of DEM
    - with residual correction
    
<br/>

5. **Clip and downscale** onto DEM with B-spline interpolation :
    - CHELSA min/mean/max temperature
    - Lapse rate
    - GMTED2010 DEM

<br/>

6. For DEM and DEM-Flat (all values = 1) :
    - **Compute** Sky View factor
    - **Compute** monthly solar radiation of DEM in function of Sky View factor
    - **Correct** monthly solar radiation with cloud cover :

$$SolarRadiation = TotalRad * (1 - 0.75 * (\frac{clouds}{10000}) ^ {3.4})$$
with $TotalRad = DiffuseRad + DirectRad$  
( and $TotalRad = \frac{TotalRad}{30}$ to have daily values )
    
<br/>

7. **Compute** quotient of solar radiation :

$$quotientSolarRadiation = \frac{SolarRadiation(DEM)}{SolarRadiation(DEM Flat)}$$


11. **Compute** Land Surface Temperature :

\begin{align}
LST =& \text{ } TemperatureRef - 4.1 * LapseRate * \frac{(Elevation - ElevationRef)}{1000} \\
& + Cst * (quotientSolarRadiation - \frac{1}{quotientSolarRadiation}) * (1 - \frac{LAI}{LAImax})
\end{align}

with $LAI = 0.01 =$ Leaf Area Index  
and $LAImax = 10 =$ cumulative LAI for all species in a grid cell from February to August

<br/>
<br/>

# Citations

- Karger, D.N., Conrad, O., Böhner, J., Kawohl, T., Kreft, H., Soria-Auza, R.W., Zimmermann, N., Peter L.H. & Kessler, M. (2016). Climatologies at high resolution for the Earth land surface areas. Scientific Data. 4. doi:10.1038/sdata.2017.122

- [CHELSA](chelsa-climate.org)
- [Earth Env](http://www.earthenv.org/)
- [ERA Interim](http://apps.ecmwf.int/datasets/data/interim-full-daily/levtype=ml/)
- [ERA5](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-pressure-levels?tab=overview)
- [SGS and NGA DEM data (GMTED2010)](https://www.usgs.gov/land-resources/eros/coastal-changes-and-impacts/gmted2010?qt-science_support_page_related_con=0#qt-science_support_page_related_con)

